package com.cs336.tutor.data.remote

import com.cs336.tutor.domain.model.JudgeResult
import com.cs336.tutor.domain.provider.ExplanationChunk
import com.cs336.tutor.domain.provider.LLMProvider
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOf
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Mock LLM provider for offline development.
 * Returns stub explanations and always-perfect judge results.
 */
@Singleton
class MockLLMProvider @Inject constructor() : LLMProvider {

    override val name: String = "Mock (Offline)"

    override suspend fun explain(
        componentId: String,
        codeLines: List<String>
    ): Flow<ExplanationChunk> {
        return flowOf(
            ExplanationChunk(
                text = "This is a stub explanation for component: $componentId\n" +
                        "Line-by-line breakdown will be generated by the real LLM provider.\n" +
                        "Configure a provider in Settings to get AI-powered explanations.",
                isComplete = true
            )
        )
    }

    override suspend fun judge(
        componentId: String,
        userCode: String,
        expectedCode: String
    ): JudgeResult {
        return JudgeResult(
            score = 1.0f,
            passed = true,
            feedback = "Mock judge: code accepted (no real validation in offline mode).",
            diff = ""
        )
    }

    override suspend fun answer(
        question: String,
        context: String
    ): Flow<ExplanationChunk> {
        return flowOf(
            ExplanationChunk(
                text = "This is a mock response. Connect a real LLM provider to answer:\n\n" +
                        "\"$question\"\n\n" +
                        "Context: $context",
                isComplete = true
            )
        )
    }

    override suspend fun generateComponent(spec: ComponentSpec): TutorComponent {
        // In mock mode, return the spec itself as a component
        return TutorComponent(
            id = spec.id,
            name = spec.name,
            description = spec.description,
            isLocked = false,
            prerequisites = spec.prerequisites,
            codeLines = spec.codeLines
        )
    }
}
