package com.cs336.tutor.domain.engine

import com.cs336.tutor.domain.model.*

object FullCodeReviewComponent {
    val spec = ComponentSpec(
        id = "fullreview",
        name = "Full Code Review",
        description = "Complete assembled code from all 10 components",
        prerequisites = listOf("bpe", "embedding", "rmsnorm", "rope", "attention", "ffn", "transformer", "lmhead", "optimizer", "training"),
        codeLines = listOf(
            CodeLineStub(1, "# ===== bpe ===== ", "", isEditable = false),
            CodeLineStub(2, "# ===== embedding ===== ", "", isEditable = false),
            CodeLineStub(3, "import torch.nn as nn", "Import PyTorch neural network module — provides nn.Module and nn.Embedding.", isEditable = true),
            CodeLineStub(4, "class Embedding(nn.Module):", "Token embedding layer. Maps integer token IDs (0 to vocab_size-1) to dense vecto", isEditable = true),
            CodeLineStub(5, "def __init__(self, vocab_size, dim):", "vocab_size = number of unique tokens. dim = embedding dimension (e.g., 4096 for ", isEditable = true),
            CodeLineStub(6, "super().__init__()", "Initialize nn.Module — registers all sub-modules and parameters.", isEditable = true),
            CodeLineStub(7, "self.embed = nn.Embedding(vocab_size, dim)", "KEY LINE: PyTorch's built-in embedding lookup. Stores a (vocab_size, dim) weight", isEditable = true),
            CodeLineStub(8, "def forward(self, x):", "Forward pass. x: token indices, shape (batch, seq_len). Returns embeddings, shap", isEditable = true),
            CodeLineStub(9, "return self.embed(x)", "Lookup each token ID in the embedding table. Gradients flow back through the sel", isEditable = true),
            CodeLineStub(10, "# ===== rmsnorm ===== ", "", isEditable = false),
            CodeLineStub(11, "# ===== rope ===== ", "", isEditable = false),
            CodeLineStub(12, "import torch", "Import PyTorch.", isEditable = false),
            CodeLineStub(13, "import math", "Import math for log and trigonometric functions.", isEditable = false),
            CodeLineStub(14, "def precompute_freqs_cis(dim, end, theta=10000.0):", "Precompute complex exponentials for all positions. This runs once at init — not ", isEditable = true),
            CodeLineStub(15, "freqs = 1.0 / (theta ** (torch.arange(0, dim, 2)[: (dim // 2)].float() / dim))", "KEY LINE: Compute frequencies on a log scale. Lower dimensions get higher freque", isEditable = true),
            CodeLineStub(16, "t = torch.arange(end)", "Create position indices [0, 1, ..., end-1].", isEditable = true),
            CodeLineStub(17, "freqs = torch.outer(t, freqs)", "Outer product: every position × every frequency → shape (seq_len, dim//2).", isEditable = true),
            CodeLineStub(18, "freqs_cis = torch.polar(torch.ones_like(freqs), freqs)", "Convert to complex numbers: polar(1, angle) = e^(i·angle) = cos(angle) + i·sin(a", isEditable = true),
            CodeLineStub(19, "return freqs_cis", "Return precomputed complex exponentials for all positions.", isEditable = false),
            CodeLineStub(20, "def apply_rotary_emb(xq, xk, freqs_cis):", "Apply rotary embeddings to query and key tensors. xq/xk have shape (batch, seq_l", isEditable = true),
            CodeLineStub(21, "xq_ = torch.view_as_complex(xq.float().reshape(*xq.shape[:-1], -1, 2))", "Reshape to pairs and view as complex numbers. Maps (real, imag) pairs → complex ", isEditable = true),
            CodeLineStub(22, "xk_ = torch.view_as_complex(xk.float().reshape(*xk.shape[:-1], -1, 2))", "Same for keys — convert to complex representation.", isEditable = false),
            CodeLineStub(23, "xq_out = torch.view_as_real(xq_ * freqs_cis).flatten(3)", "Rotate queries: multiply complex Q by complex cis → rotates by position angle. T", isEditable = true),
            CodeLineStub(24, "xk_out = torch.view_as_real(xk_ * freqs_cis).flatten(3)", "Rotate keys: same operation. This encodes relative position into the dot product", isEditable = true),
            CodeLineStub(25, "return xq_out.type_as(xq), xk_out.type_as(xk)", "Cast back to original dtype.", isEditable = true),
            CodeLineStub(26, "# ===== attention ===== ", "", isEditable = false),
            CodeLineStub(27, "import torch.nn as nn", "Import PyTorch neural network module.", isEditable = true),
            CodeLineStub(28, "import torch.nn.functional as F", "Import functional API for softmax.", isEditable = false),
            CodeLineStub(29, "class Attention(nn.Module):", "Multi-head causal self-attention module.", isEditable = true),
            CodeLineStub(30, "def __init__(self, dim, n_heads):", "dim = model dimension, n_heads = number of attention heads. head_dim = dim // n_", isEditable = true),
            CodeLineStub(31, "super().__init__()", "Initialize nn.Module — registers all sub-modules and parameters.", isEditable = true),
            CodeLineStub(32, "self.n_heads = n_heads", "Store number of heads.", isEditable = false),
            CodeLineStub(33, "self.head_dim = dim // n_heads", "Each head operates on dim//n_heads dimensional subspace.", isEditable = true),
            CodeLineStub(34, "self.wq = nn.Linear(dim, dim, bias=False)", "Query projection. bias=False because we use RoPE (no absolute position — bias wo", isEditable = true),
            CodeLineStub(35, "self.wk = nn.Linear(dim, dim, bias=False)", "Key projection. Same shape as query.", isEditable = false),
            CodeLineStub(36, "self.wv = nn.Linear(dim, dim, bias=False)", "Value projection.", isEditable = false),
            CodeLineStub(37, "self.wo = nn.Linear(dim, dim, bias=False)", "Output projection combines all head outputs.", isEditable = true),
            CodeLineStub(38, "def forward(self, x, freqs_cis, mask=None):", "Forward pass. x: (batch, seq_len, dim). freqs_cis: precomputed RoPE frequencies.", isEditable = true),
            CodeLineStub(39, "b, s, d = x.shape", "Unpack batch, sequence length, and model dimension.", isEditable = true),
            CodeLineStub(40, "xq = self.wq(x).view(b, s, self.n_heads, self.head_dim)", "Project to queries and reshape: (batch, seq, dim) → (batch, seq, n_heads, head_d", isEditable = true),
            CodeLineStub(41, "xk = self.wk(x).view(b, s, self.n_heads, self.head_dim)", "Same for keys.", isEditable = false),
            CodeLineStub(42, "xv = self.wv(x).view(b, s, self.n_heads, self.head_dim)", "Same for values.", isEditable = false),
            CodeLineStub(43, "xq, xk = apply_rotary_emb(xq, xk, freqs_cis)", "Apply RoPE to queries and keys — encodes position into attention scores.", isEditable = true),
            CodeLineStub(44, "scores = torch.matmul(xq, xk.transpose(2, 3)) / math.sqrt(self.head_dim)", "THE CORE: Scaled dot-product. Q·K^T divided by sqrt(d_k) prevents softmax satura", isEditable = true),
            CodeLineStub(45, "if mask is not None: scores = scores + mask", "Apply causal mask (upper triangle = -inf) so position i can only attend to posit", isEditable = true),
            CodeLineStub(46, "scores = F.softmax(scores, dim=-1)", "Normalize attention weights to sum to 1. Each row is a probability distribution ", isEditable = true),
            CodeLineStub(47, "output = torch.matmul(scores, xv)", "Weighted sum of values: each position combines values from all positions it can ", isEditable = true),
            CodeLineStub(48, "output = output.transpose(1, 2).contiguous().view(b, s, d)", "Reshape back: (batch, n_heads, seq, head_dim) → (batch, seq, dim).", isEditable = true),
            CodeLineStub(49, "return self.wo(output)", "Output projection blends information across all heads.", isEditable = true),
            CodeLineStub(50, "# ===== ffn ===== ", "", isEditable = false),
            CodeLineStub(51, "import torch.nn as nn", "Import PyTorch neural network module.", isEditable = true),
            CodeLineStub(52, "import torch.nn.functional as F", "SiLU activation is in F.silu().", isEditable = false),
            CodeLineStub(53, "class FeedForward(nn.Module):", "SwiGLU feed-forward network: expands to hidden_dim, applies gated activation, pr", isEditable = true),
            CodeLineStub(54, "def __init__(self, dim, hidden_dim=None):", "dim = model dimension (e.g. 4096). hidden_dim typically = 8/3 * dim ≈ 14336 for ", isEditable = true),
            CodeLineStub(55, "super().__init__()", "Initialize nn.Module — registers all sub-modules and parameters.", isEditable = true),
            CodeLineStub(56, "hidden_dim = hidden_dim or 4 * dim", "Default: 4x expansion. LLaMA-style uses 8/3 * dim, but 4x is the classic Transfo", isEditable = true),
            CodeLineStub(57, "self.w1 = nn.Linear(dim, hidden_dim, bias=False)", "Gate projection: produces gating values.", isEditable = true),
            CodeLineStub(58, "self.w3 = nn.Linear(dim, hidden_dim, bias=False)", "Up projection: produces values to be gated.", isEditable = true),
            CodeLineStub(59, "self.w2 = nn.Linear(hidden_dim, dim, bias=False)", "Down projection: projects back to model dim.", isEditable = true),
            CodeLineStub(60, "def forward(self, x):", "SwiGLU forward: gate = SiLU(x·w1), up = x·w3, output = (gate ⊙ up) · w2.", isEditable = true),
            CodeLineStub(61, "return self.w2(F.silu(self.w1(x)) * self.w3(x))", "KEY LINE: The full SwiGLU formula in one line! SiLU(w1·x) acts as a learned gate", isEditable = true),
            CodeLineStub(62, "# ===== transformer ===== ", "", isEditable = false),
            CodeLineStub(63, "import torch.nn as nn", "Import PyTorch neural network module.", isEditable = true),
            CodeLineStub(64, "from rmsnorm import RMSNorm", "Import our RMSNorm implementation.", isEditable = false),
            CodeLineStub(65, "from attention import Attention", "Import our Attention implementation.", isEditable = false),
            CodeLineStub(66, "from ffn import FeedForward", "Import our FFN implementation.", isEditable = false),
            CodeLineStub(67, "class TransformerBlock(nn.Module):", "The complete building block of a decoder-only Transformer. Each block transforms", isEditable = true),
            CodeLineStub(68, "def __init__(self, dim, n_heads):", "Initialize all sub-components: 2 RMSNorm layers, 1 Attention, 1 FFN.", isEditable = true),
            CodeLineStub(69, "super().__init__()", "Initialize nn.Module — registers all sub-modules and parameters.", isEditable = true),
            CodeLineStub(70, "self.attention = Attention(dim, n_heads)", "Multi-head self-attention sub-layer.", isEditable = true),
            CodeLineStub(71, "self.feed_forward = FeedForward(dim)", "SwiGLU feed-forward sub-layer.", isEditable = true),
            CodeLineStub(72, "self.attention_norm = RMSNorm(dim)", "PRE-attention normalization (Pre-LN architecture). Normalizes before attention, ", isEditable = true),
            CodeLineStub(73, "self.ffn_norm = RMSNorm(dim)", "PRE-FFN normalization. Same pattern: normalize before the sub-layer.", isEditable = false),
            CodeLineStub(74, "def forward(self, x, freqs_cis, mask=None):", "Complete forward pass through one Transformer block: norm → attn → +residual → n", isEditable = true),
            CodeLineStub(75, "h = x + self.attention(self.attention_norm(x), freqs_cis, mask)", "KEY LINE: Pre-LN attention with residual. (1) RMSNorm the input, (2) run attenti", isEditable = true),
            CodeLineStub(76, "out = h + self.feed_forward(self.ffn_norm(h))", "Same pattern for FFN: normalize → FFN → add residual. out = h + ffn(norm(h)).", isEditable = true),
            CodeLineStub(77, "return out", "Output has same shape as input (batch, seq_len, dim). This enables stacking mult", isEditable = true),
            CodeLineStub(78, "# ===== lmhead ===== ", "", isEditable = false),
            CodeLineStub(79, "import torch.nn as nn", "Import PyTorch neural network module for nn.Module and nn.Linear.", isEditable = true),
            CodeLineStub(80, "class LMHead(nn.Module):", "The final layer that converts hidden states to token predictions. Maps (batch, s", isEditable = true),
            CodeLineStub(81, "def __init__(self, dim, vocab_size):", "dim = model dimension. vocab_size = number of tokens in vocabulary.", isEditable = true),
            CodeLineStub(82, "super().__init__()", "Initialize nn.Module — registers all sub-modules and parameters.", isEditable = true),
            CodeLineStub(83, "self.lm_head = nn.Linear(dim, vocab_size, bias=False)", "KEY LINE: Linear projection from model dimension to vocabulary size. bias=False ", isEditable = true),
            CodeLineStub(84, "def forward(self, x):", "Forward pass: project each positions hidden state to vocabulary logits.", isEditable = true),
            CodeLineStub(85, "return self.lm_head(x)", "Output shape: (batch, seq, vocab_size). Each position has a score for every toke", isEditable = true),
            CodeLineStub(86, "# ===== optimizer ===== ", "", isEditable = false),
            CodeLineStub(87, "import torch", "Import PyTorch — provides tensor operations and automatic differentiation.", isEditable = true),
            CodeLineStub(88, "optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)", "Classic Adam (without weight decay). Simpler but less effective for large models", isEditable = false),
            CodeLineStub(89, "# Adam update rule:", "Comment: the three equations below describe how Adam updates parameters.", isEditable = true),
            CodeLineStub(90, "# m_t = beta1 * m_{t-1} + (1-beta1) * g_t  (momentum)", "First moment (mean of gradients). Smooths noisy gradients — like a rolling avera", isEditable = false),
            CodeLineStub(91, "# v_t = beta2 * v_{t-1} + (1-beta2) * g_t²  (RMS)", "Second moment (uncentered variance). Adapts learning rate per-parameter.", isEditable = false),
            CodeLineStub(92, "# theta_t = theta_{t-1} - lr * m_t / (sqrt(v_t) + eps)  (update)", "Parameter update: divide momentum by sqrt of adaptive learning rate. Each parame", isEditable = false),
            CodeLineStub(93, "# ===== training ===== ", "", isEditable = false),
            CodeLineStub(94, "import torch", "Import PyTorch — provides tensor operations and automatic differentiation.", isEditable = true),
            CodeLineStub(95, "import torch.nn.functional as F", "Cross-entropy loss function.", isEditable = false),
            CodeLineStub(96, "def train_step(model, batch, optimizer):", "One complete training step: forward → loss → backward → update. batch = (input_i", isEditable = true),
            CodeLineStub(97, "model.train()", "Set model to training mode. This enables dropout, batch norm, etc.", isEditable = true),
            CodeLineStub(98, "logits = model(batch)", "Forward pass through the entire model. logits shape: (batch, seq_len, vocab_size", isEditable = true),
            CodeLineStub(99, "loss = F.cross_entropy(", "KEY LINE: Standard language modeling loss. Compares predicted token distribution", isEditable = true),
            CodeLineStub(100, "logits.view(-1, logits.size(-1)),", "Flatten logits: (batch*seq_len, vocab_size). We predict each token independently", isEditable = true),
            CodeLineStub(101, "batch.view(-1)", "Flatten targets: (batch*seq_len,). Must match logits' first dimension.", isEditable = true),
            CodeLineStub(102, ")", "", isEditable = false),
            CodeLineStub(103, "loss.backward()", "Backpropagation: computes gradients for all parameters via automatic differentia", isEditable = true),
            CodeLineStub(104, "optimizer.step()", "Apply gradients: update all parameters using the optimizer's rule (Adam, SGD, et", isEditable = true),
            CodeLineStub(105, "return loss.item()", "Return scalar loss value for logging/monitoring.", isEditable = true),
        ),
        exercises = listOf(
            Exercise("Review assembled code", "Check consistency across components", "", emptyList()),
            Exercise("Verify dimensions", "Trace shapes at each stage", "", emptyList())
        ),
        judgeCriteria = listOf(
            JudgeCriterion("All 10 components present and connected", 0.4f),
            JudgeCriterion("Tensor dimensions consistent", 0.3f),
            JudgeCriterion("PyTorch best practices", 0.3f)
        )
    )
}
